### ISSUE TITLE
ImageJ-Canvas listener

### ISSUE THREAD

**Issue by mutterer** [Bio7/EclipseImageJ1Plugin#1] opened 2018-10-22 13:46 UTC
It would be nice if the ImageJ-Canvas view had listeners from the beginning, even when empty. Currently, there needs to be an image in it, and you need to click the image to get the listeners and be able to use IJ shortcuts.

**Comment by Bio7** [comment] 2018-10-23 07:15
Duplicate of issue #2

**Closed as completed by Bio7** 2018-10-23 07:15 UTC
